[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "selector"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
]

[tool.setuptools.packages.find]
where = ["."]
namespaces = false
